# WELCOME TO THE OFFICAL SLEEP-MOST PLUGIN
# AUTHORS: MrGeneralQ, HorrendousEntity
# VERSION: 4.6.1
# SUPPORT NEEDED? Join our discord at --> https://discord.pseudonova.com/ WE ARE HAPPY TO HELP YOU FURTHER!


# WARNING: SUPPORT IS ONLY GIVEN TO THE LATEST VERSION
update-checker-enabled: true

sleep:
  # for each world, you can create different configurations
  world:
    enabled: true
    calculation-method: percentage
    percentage-required: 0.50
    players-required: 5
    mob-no-target: true
    use-exempt: false
    use-afk: false
    prevent-sleep: false
    prevent-phantom: false
    nightcycle-animation: false
    storm-sleep: true

  world2:
    enabled: false
    calculation-method: percentage
    percentage-required: 0.50
    players-required: 5
    mob-no-target: true
    use-exempt: false
    use-afk: false
    prevent-sleep: false
    prevent-phantom: false
    nightcycle-animation: false
    storm-sleep: true


titles:
  night-skipped:
    enabled: false
    title: '&aNight skipped'
    subtitle: '&bGood morning sunshine!'
  storm-skipped:
    enabled: false
    title: '&eStorm skipped'
    subtitle: '&bWhat a weather...'


# Add sound effects after skipping the night or storm
sounds:
  night-skipped:
    enabled: false
    sound: UI_TOAST_CHALLENGE_COMPLETE
  storm-skipped:
    enabled: false
    sound: ENTITY_WITHER_SPAWN


# specify the time which the world will be set after reset
time-after-reset: 0

messages:
  prefix: '&7[&bSleep-Most&7]'

  #time in seconds for message cooldown when a player goes to sleep
  #default 10 seconds
  cooldown: 10

  #message when the night got skipped
  night-skipped: '&bThe night was skipped!'

  #message when the storm got skipped
  storm-skipped: '&bThe storm was skipped!'

  #message format to show how many players are required to sleep
  players-left-night: '&bSleeping to skip night &f[&c%sleeping%/%required%&f]&b!'
  players-left-storm: '&bSleeping to skip the storm &f[&c%sleeping%/%required%&f]&b!'
  sleep-prevented: '&cYou cannot sleep in this world!'
  no-sleep-storm: '&cYou cannot sleep during a thunderstorm'