# WELCOME TO THE OFFICAL SLEEP-MOST PLUGIN
# CREATED BY MrGeneralQ
# VERSION: 4.5.3
# SUPPORT NEEDED? Join our discord at --> https://discord.pseudonova.com/ WE ARE HAPPY TO HELP YOU FURTHER!


# WARNING: SUPPORT IS ONLY GIVEN TO THE LATEST VERSION
update-checker-enabled: true

sleep:
  # for each world, you can create different configurations
  world:
    enabled: true
    percentage-required: 0.50
    mob-no-target: true
    use-exempt: false
    use-afk: false
    prevent-sleep: false
    prevent-phantom: false
    nightcycle-animation: false
    storm-sleep: true

  world2:
    enabled: false
    percentage-required: 0.50
    mob-no-target: true
    use-exempt: false
    use-afk: false
    prevent-sleep: false
    prevent-phantom: false
    nightcycle-animation: false
    storm-sleep: true

# specify the time which the world will be set after reset
time-after-reset: 0

messages:
  prefix: '&7[&bSleep-Most&7]'

  #time in seconds for message cooldown when a player goes to sleep
  #default 10 seconds
  cooldown: 10

  #message when the night got skipped
  night-skipped: '&bThe night was skipped!'

  #message when the storm got skipped
  storm-skipped: '&bThe storm was skipped!'

  #message format to show how many players are required to sleep
  players-left-night: '&bSleeping to skip night &f[&c%sleeping%/%required%&f]&b!'
  players-left-storm: '&bSleeping to skip the storm &f[&c%sleeping%/%required%&f]&b!'
  sleep-prevented: '&cYou cannot sleep in this world!'
  no-sleep-storm: '&cYou cannot sleep during a thunderstorm'